version: '3.1'

services:

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Rafiki_FMIS_DB
    restart: unless-stopped